import { defineMapping } from "./types";

/**
 * ServiceTitan jobs-and-invoices export with line items and costs. A row is
 * one invoice line item, with its invoice's and job's columns repeated (they
 * must agree across the rows of one invoice). A row with a Job # but no
 * Invoice # is a job without an invoice (a callback, a canceled job or an
 * install still in progress). All rows of one invoice import together or not
 * at all, so an invoice is never left half-imported.
 */
export const invoicesMapping = defineMapping({
  type: "invoices",
  label: "Jobs and invoices with line items (and costs)",
  rowMeaning: "one invoice line item (or a job without an invoice)",
  fields: {
    // Job
    jobNumber: { headers: ["Job #", "Job Number", "Job ID"] },
    jobType: { headers: ["Job Type"] },
    jobSummary: { headers: ["Job Summary", "Job Description"] },
    jobStatus: { headers: ["Job Status"] },
    priority: { headers: ["Priority", "Job Priority"] },
    jobSource: { headers: ["Job Source", "Campaign Category", "Source"] },
    bookedBy: { headers: ["Booked By", "Booked By ID"] },
    bookedOn: { headers: ["Booked On", "Job Created On", "Created Date"] },
    completedOn: { headers: ["Completed On", "Job Completion Date", "Completion Date"] },
    soldBy: { headers: ["Sold By", "Sold By ID"] },
    leadBy: { headers: ["Lead Generated By", "Lead Source Technician", "Lead Generated By ID"] },
    recallFor: { headers: ["Recall For", "Recall For Job #", "Callback Of Job #"] },
    recallTechCaused: { headers: ["Recall Tech Caused", "Callback Tech Caused"] },
    recallReason: { headers: ["Recall Reason", "Callback Reason"] },
    // Customer and place
    customerId: { headers: ["Customer ID", "Customer #"], required: true },
    customerName: { headers: ["Customer Name", "Customer"], informational: true },
    locationId: { headers: ["Location ID", "Location #"] },
    businessUnit: { headers: ["Business Unit", "Job Business Unit"], required: true },
    poNumber: { headers: ["PO Number", "PO #", "Customer PO"] },
    // Invoice
    invoiceNumber: { headers: ["Invoice #", "Invoice Number", "Invoice ID"], required: true },
    invoiceDate: { headers: ["Invoice Date"], required: true },
    dueDate: { headers: ["Due Date", "Invoice Due Date"] },
    invoiceStatus: { headers: ["Invoice Status", "Status"] },
    billingStage: { headers: ["Billing Stage", "Progress Billing Stage"] },
    invoiceSummary: { headers: ["Invoice Summary", "Invoice Description"] },
    subtotal: { headers: ["Subtotal", "Sub Total", "Invoice Subtotal"] },
    discount: { headers: ["Discount", "Discount Total", "Invoice Discount"] },
    tax: { headers: ["Tax", "Sales Tax", "Tax Total"] },
    total: { headers: ["Total", "Invoice Total", "Total Amount"], required: true },
    balance: { headers: ["Balance", "Balance Due", "Invoice Balance"], required: true },
    paidOn: { headers: ["Paid On", "Paid In Full On", "Paid Date"] },
    // Line item
    lineId: { headers: ["Invoice Item ID", "Invoice Line ID", "Line ID"] },
    lineNumber: { headers: ["Line #", "Line Number", "Item Order"] },
    itemCode: { headers: ["Item Code", "SKU", "Code"] },
    itemType: { headers: ["Item Type"] },
    description: { headers: ["Description", "Item Description", "Item Name"] },
    quantity: { headers: ["Quantity", "Qty"] },
    unitPrice: { headers: ["Unit Price", "Price", "Item Price"] },
    lineDiscount: { headers: ["Item Discount", "Line Discount"] },
    lineAmount: { headers: ["Item Total", "Line Total", "Amount"] },
    taxable: { headers: ["Taxable", "Is Taxable"] },
    lineTax: { headers: ["Item Tax", "Line Tax"] },
    cost: { headers: ["Cost", "Item Cost", "Total Cost"] },
  },
});
