/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as FieldRouteImport } from "./routes/_field"
import { Route as OfficeRouteImport } from "./routes/_office"
import { Route as GpsTestRouteImport } from "./routes/gps-test"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as FieldTechRouteImport } from "./routes/_field/tech"
import { Route as OfficeEmployeesRouteImport } from "./routes/_office/employees"
import { Route as OfficePricebookRouteImport } from "./routes/_office/pricebook"
import { Route as OfficeCustomersIndexRouteImport } from "./routes/_office/customers/index"
import { Route as OfficeCustomersCustomerIdRouteImport } from "./routes/_office/customers/$customerId"
import { Route as OfficeImportsIndexRouteImport } from "./routes/_office/imports/index"
import { Route as OfficeImportsBatchIdRouteImport } from "./routes/_office/imports/$batchId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: "/_field",
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: "/_office",
  getParentRoute: () => rootRouteImport,
} as any)
const GpsTestRoute = GpsTestRouteImport.update({
  id: "/gps-test",
  path: "/gps-test",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const FieldTechRoute = FieldTechRouteImport.update({
  id: "/tech",
  path: "/tech",
  getParentRoute: () => FieldRoute,
} as any)
const OfficeEmployeesRoute = OfficeEmployeesRouteImport.update({
  id: "/employees",
  path: "/employees",
  getParentRoute: () => OfficeRoute,
} as any)
const OfficePricebookRoute = OfficePricebookRouteImport.update({
  id: "/pricebook",
  path: "/pricebook",
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeCustomersIndexRoute = OfficeCustomersIndexRouteImport.update({
  id: "/customers/",
  path: "/customers/",
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeCustomersCustomerIdRoute =
  OfficeCustomersCustomerIdRouteImport.update({
    id: "/customers/$customerId",
    path: "/customers/$customerId",
    getParentRoute: () => OfficeRoute,
  } as any)
const OfficeImportsIndexRoute = OfficeImportsIndexRouteImport.update({
  id: "/imports/",
  path: "/imports/",
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeImportsBatchIdRoute = OfficeImportsBatchIdRouteImport.update({
  id: "/imports/$batchId",
  path: "/imports/$batchId",
  getParentRoute: () => OfficeRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/gps-test": typeof GpsTestRoute
  "/login": typeof LoginRoute
  "/tech": typeof FieldTechRoute
  "/employees": typeof OfficeEmployeesRoute
  "/pricebook": typeof OfficePricebookRoute
  "/customers/$customerId": typeof OfficeCustomersCustomerIdRoute
  "/imports/$batchId": typeof OfficeImportsBatchIdRoute
  "/customers/": typeof OfficeCustomersIndexRoute
  "/imports/": typeof OfficeImportsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/gps-test": typeof GpsTestRoute
  "/login": typeof LoginRoute
  "/tech": typeof FieldTechRoute
  "/employees": typeof OfficeEmployeesRoute
  "/pricebook": typeof OfficePricebookRoute
  "/customers/$customerId": typeof OfficeCustomersCustomerIdRoute
  "/imports/$batchId": typeof OfficeImportsBatchIdRoute
  "/customers": typeof OfficeCustomersIndexRoute
  "/imports": typeof OfficeImportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_field": typeof FieldRouteWithChildren
  "/_office": typeof OfficeRouteWithChildren
  "/gps-test": typeof GpsTestRoute
  "/login": typeof LoginRoute
  "/_field/tech": typeof FieldTechRoute
  "/_office/employees": typeof OfficeEmployeesRoute
  "/_office/pricebook": typeof OfficePricebookRoute
  "/_office/customers/$customerId": typeof OfficeCustomersCustomerIdRoute
  "/_office/imports/$batchId": typeof OfficeImportsBatchIdRoute
  "/_office/customers/": typeof OfficeCustomersIndexRoute
  "/_office/imports/": typeof OfficeImportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/gps-test"
    | "/login"
    | "/tech"
    | "/employees"
    | "/pricebook"
    | "/customers/$customerId"
    | "/imports/$batchId"
    | "/customers/"
    | "/imports/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/gps-test"
    | "/login"
    | "/tech"
    | "/employees"
    | "/pricebook"
    | "/customers/$customerId"
    | "/imports/$batchId"
    | "/customers"
    | "/imports"
  id:
    | "__root__"
    | "/"
    | "/_field"
    | "/_office"
    | "/gps-test"
    | "/login"
    | "/_field/tech"
    | "/_office/employees"
    | "/_office/pricebook"
    | "/_office/customers/$customerId"
    | "/_office/imports/$batchId"
    | "/_office/customers/"
    | "/_office/imports/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FieldRoute: typeof FieldRouteWithChildren
  OfficeRoute: typeof OfficeRouteWithChildren
  GpsTestRoute: typeof GpsTestRoute
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_field": {
      id: "/_field"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_office": {
      id: "/_office"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/gps-test": {
      id: "/gps-test"
      path: "/gps-test"
      fullPath: "/gps-test"
      preLoaderRoute: typeof GpsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_field/tech": {
      id: "/_field/tech"
      path: "/tech"
      fullPath: "/tech"
      preLoaderRoute: typeof FieldTechRouteImport
      parentRoute: typeof FieldRoute
    }
    "/_office/employees": {
      id: "/_office/employees"
      path: "/employees"
      fullPath: "/employees"
      preLoaderRoute: typeof OfficeEmployeesRouteImport
      parentRoute: typeof OfficeRoute
    }
    "/_office/pricebook": {
      id: "/_office/pricebook"
      path: "/pricebook"
      fullPath: "/pricebook"
      preLoaderRoute: typeof OfficePricebookRouteImport
      parentRoute: typeof OfficeRoute
    }
    "/_office/customers/": {
      id: "/_office/customers/"
      path: "/customers"
      fullPath: "/customers/"
      preLoaderRoute: typeof OfficeCustomersIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    "/_office/customers/$customerId": {
      id: "/_office/customers/$customerId"
      path: "/customers/$customerId"
      fullPath: "/customers/$customerId"
      preLoaderRoute: typeof OfficeCustomersCustomerIdRouteImport
      parentRoute: typeof OfficeRoute
    }
    "/_office/imports/": {
      id: "/_office/imports/"
      path: "/imports"
      fullPath: "/imports/"
      preLoaderRoute: typeof OfficeImportsIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    "/_office/imports/$batchId": {
      id: "/_office/imports/$batchId"
      path: "/imports/$batchId"
      fullPath: "/imports/$batchId"
      preLoaderRoute: typeof OfficeImportsBatchIdRouteImport
      parentRoute: typeof OfficeRoute
    }
  }
}

interface FieldRouteChildren {
  FieldTechRoute: typeof FieldTechRoute
}

const FieldRouteChildren: FieldRouteChildren = {
  FieldTechRoute: FieldTechRoute,
}

const FieldRouteWithChildren = FieldRoute._addFileChildren(FieldRouteChildren)

interface OfficeRouteChildren {
  OfficeEmployeesRoute: typeof OfficeEmployeesRoute
  OfficePricebookRoute: typeof OfficePricebookRoute
  OfficeCustomersCustomerIdRoute: typeof OfficeCustomersCustomerIdRoute
  OfficeImportsBatchIdRoute: typeof OfficeImportsBatchIdRoute
  OfficeCustomersIndexRoute: typeof OfficeCustomersIndexRoute
  OfficeImportsIndexRoute: typeof OfficeImportsIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeEmployeesRoute: OfficeEmployeesRoute,
  OfficePricebookRoute: OfficePricebookRoute,
  OfficeCustomersCustomerIdRoute: OfficeCustomersCustomerIdRoute,
  OfficeImportsBatchIdRoute: OfficeImportsBatchIdRoute,
  OfficeCustomersIndexRoute: OfficeCustomersIndexRoute,
  OfficeImportsIndexRoute: OfficeImportsIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FieldRoute: FieldRouteWithChildren,
  OfficeRoute: OfficeRouteWithChildren,
  GpsTestRoute: GpsTestRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
