import { estimateCost } from "@/lib/ai/models";
import { ANALYSIS_PROMPT_VERSION, CHAT_PROMPT_VERSION, COACH_PROMPT_VERSION } from "@/lib/ai/prompts/coach";
import { EXTRACTION_PROMPT_VERSION } from "@/lib/ai/prompts/extraction";
import type { CoachBrief, ExtractionResult } from "@/lib/ai/schemas";
import type {
  AiProvider,
  AiResult,
  ChatRequest,
  CoachRequest,
  DeepAnalysisRequest,
  ExtractKpisRequest,
} from "@/lib/ai/types";

/** Deterministic pseudo-random in [0,1) so dev runs are reproducible. */
function hashUnit(seed: string): number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return ((h >>> 0) % 10000) / 10000;
}

/**
 * Offline stand-in for the Anthropic provider.
 *
 * Enabled with AI_DEV_MODE=true. It exercises the entire pipeline — schema
 * validation, confidence banding, conflict detection, review queue, cost
 * ledger — without a network call or a cent of spend. Values are obviously
 * synthetic and are never presented as real Victra data.
 */
export class MockAiProvider implements AiProvider {
  readonly name = "mock";

  async extractKpis(request: ExtractKpisRequest): Promise<AiResult<ExtractionResult>> {
    const labels = request.images.map((i) => i.label);
    const kpis = request.knownKpis.length > 0 ? request.knownKpis : FALLBACK_KPIS;

    const metrics = kpis.map((kpi, index) => {
      const seed = `${kpi.key}:${labels.length}`;
      const value = Math.round(hashUnit(seed) * 14) + 1;
      // One deliberately shaky reading per batch so the review flow is visible.
      const confidence = index === 1 ? 0.62 : 0.9 + hashUnit(`c:${seed}`) * 0.09;
      return {
        key: kpi.key,
        display_name: kpi.displayName,
        value,
        raw_text: String(value),
        unit: "count" as const,
        confidence: Math.round(confidence * 100) / 100,
        source_image: labels[index % Math.max(labels.length, 1)] ?? "screenshot_1",
        period_start: null,
        period_end: null,
        notes: index === 1 ? "Mock provider: low-confidence sample reading." : null,
      };
    });

    const data: ExtractionResult = {
      reporting_period: { start: null, end: null, label: null, confidence: 0.4 },
      metrics,
      unreadable_images: [],
      notes: "Generated by the mock AI provider (AI_DEV_MODE=true). Values are synthetic.",
    };

    return this.result(data, data, request.model, EXTRACTION_PROMPT_VERSION, {
      inputTokens: 1200 * Math.max(labels.length, 1),
      outputTokens: 380,
    });
  }

  async generateCoach(request: CoachRequest): Promise<AiResult<CoachBrief>> {
    const data: CoachBrief = {
      overall_status: "AT_RISK",
      headline: "Mock coaching brief — AI_DEV_MODE is on, so no model was called.",
      biggest_win: { kpi: "Sample KPI", reason: "This placeholder stands in for the model's analysis." },
      biggest_problem: { kpi: "Sample KPI", reason: "Set AI_DEV_MODE=false and add an API key for real coaching." },
      priorities: [
        { action: "Turn off AI_DEV_MODE to get real coaching.", why: "The mock provider returns fixed text.", impact: "HIGH" },
        { action: "Upload a real KPI snapshot.", why: "The coach reasons from confirmed observations.", impact: "MEDIUM" },
        { action: "Set your goals for the period.", why: "Pacing needs a target to measure against.", impact: "MEDIUM" },
      ],
      opportunity: "Placeholder opportunity text from the mock provider.",
      forecast: "Placeholder forecast text from the mock provider.",
      one_thing: "Configure ANTHROPIC_API_KEY to enable the real AI Coach.",
    };
    return this.result(data, data, request.model, COACH_PROMPT_VERSION, {
      inputTokens: 900,
      outputTokens: 260,
    });
  }

  async answerQuestion(request: ChatRequest): Promise<AiResult<string>> {
    const answer = `Mock provider (AI_DEV_MODE=true) — no model was called, so this is not a real answer to "${request.question}". The context assembled for the model was ${request.context.length} characters. Set AI_DEV_MODE=false and provide ANTHROPIC_API_KEY for real answers.`;
    return this.result(answer, [{ type: "text", text: answer }], request.model, CHAT_PROMPT_VERSION, {
      inputTokens: 700,
      outputTokens: 90,
    });
  }

  async deepAnalyze(request: DeepAnalysisRequest): Promise<AiResult<string>> {
    const answer = `## Mock deep analysis\n\nAI_DEV_MODE is enabled, so no model was called.${
      request.focus ? `\n\nRequested focus: ${request.focus}` : ""
    }\n\nDisable AI_DEV_MODE and set ANTHROPIC_API_KEY to run a real strategic analysis.`;
    return this.result(answer, [{ type: "text", text: answer }], request.model, ANALYSIS_PROMPT_VERSION, {
      inputTokens: 1100,
      outputTokens: 200,
    });
  }

  private async result<T>(
    data: T,
    raw: unknown,
    model: string,
    promptVersion: string,
    usage: { inputTokens: number; outputTokens: number },
  ): Promise<AiResult<T>> {
    // A little latency keeps loading states honest during development.
    await new Promise((resolve) => setTimeout(resolve, 180));
    return {
      data,
      raw,
      meta: {
        provider: this.name,
        model,
        promptVersion,
        usage: { ...usage, cacheReadTokens: 0, cacheCreationTokens: 0 },
        // Costed as if real, so the usage dashboard is exercised in dev too.
        estimatedCostUsd: estimateCost(model, usage),
        latencyMs: 180,
      },
    };
  }
}

const FALLBACK_KPIS = [
  { key: "internet", displayName: "Internet", aliases: [] },
  { key: "vmp", displayName: "VMP", aliases: [] },
  { key: "smb", displayName: "SMB", aliases: [] },
  { key: "cpg", displayName: "CPG", aliases: [] },
];
